services:
    callme:
        image: mirotalk/cme:latest
        container_name: callme
        hostname: callme
        volumes:
            - .env:/src/.env:ro
            - ./app/:/src/app/:ro
            - ./public/:/src/public/:ro
        restart: unless-stopped
        ports:
            - '${PORT}:${PORT}'
